version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    environment:      
      - discovery.type=single-node    
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    
  web:
    build: .
    working_dir: /
    depends_on:
        - elasticsearch
    volumes:
      - './app:/app'   
    ports:
      - '8989:8989'

  